package com.jspiders.servlet_Netflix;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class NetflixServlet  extends HttpServlet{

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        // Set the content type of the response to "text/html"
        response.setContentType("text/html");

        // Get the PrintWriter object to write the response
        PrintWriter writer = response.getWriter();
        writer.print("<!DOCTYPE html>\r\n"
        		+ "<html lang=\"en\">\r\n"
        		+ "\r\n"
        		+ "<head>\r\n"
        		+ "    <meta charset=\"UTF-8\">\r\n"
        		+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
        		+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
        		+ "    <title>Document</title>\r\n"
        		+ "    <!-- <link rel=\"stylesheet\" href=\"pr.css\"> -->\r\n"
        		+ "</head>\r\n"
        		+ "<style>\r\n"
        		+ "    body{\r\n"
        		+ "   height: 100%;\r\n"
        		+ "   width: 100%;\r\n"
        		+ "   background-image: url(https://st1.bgr.in/wp-content/uploads/2022/04/Untitled-design-2022-04-20T095244.884.jpg);\r\n"
        		+ "   background-repeat: no-repeat;\r\n"
        		+ "   background-size: cover;\r\n"
        		+ "   /* padding: 0; */\r\n"
        		+ "   margin: 0;\r\n"
        		+ "\r\n"
        		+ "}\r\n"
        		+ "\r\n"
        		+ "#v1{\r\n"
        		+ "     font-size: 50px;\r\n"
        		+ "     margin-left: 60px;\r\n"
        		+ "     margin-bottom: -90px;\r\n"
        		+ "     color:red;\r\n"
        		+ "}\r\n"
        		+ "#a1{\r\n"
        		+ "    font-size: 50px;\r\n"
        		+ "    margin-left: 60px;\r\n"
        		+ "    margin-top: -60px;\r\n"
        		+ "    /* margin-bottom: -165px; */\r\n"
        		+ "    color:red;\r\n"
        		+ "}\r\n"
        		+ "h1{\r\n"
        		+ "    margin-left: 450px;\r\n"
        		+ "    margin-top: 300px;\r\n"
        		+ "   font-size: 40px;\r\n"
        		+ "   color: white;\r\n"
        		+ "}\r\n"
        		+ "h3{\r\n"
        		+ "    margin-left: 620px;\r\n"
        		+ "    margin-top: 30px;\r\n"
        		+ "    color: white;\r\n"
        		+ "}\r\n"
        		+ "h4{\r\n"
        		+ "    margin-left: 500px;\r\n"
        		+ "    margin-top: 40px;\r\n"
        		+ "    color: white;\r\n"
        		+ "    font-size: large;\r\n"
        		+ "    \r\n"
        		+ "}\r\n"
        		+ "#l1{\r\n"
        		+ "    height: 40px;\r\n"
        		+ "    width: 550px;\r\n"
        		+ "    margin-left: 400px;\r\n"
        		+ "    margin-top: 10px;\r\n"
        		+ "}\r\n"
        		+ "#l2{\r\n"
        		+ "    height: 45px;\r\n"
        		+ "    font-size: large;\r\n"
        		+ "    width: 200px;\r\n"
        		+ "    background-color: red;\r\n"
        		+ "    color: white;\r\n"
        		+ "}\r\n"
        		+ "#b1{\r\n"
        		+ "    height: 30px;\r\n"
        		+ "    width: 80px;\r\n"
        		+ "    margin-top: 40px;\r\n"
        		+ "    background-color: black;\r\n"
        		+ "    color: white;\r\n"
        		+ "}\r\n"
        		+ "#k1{\r\n"
        		+ "    margin-left: 1100px;\r\n"
        		+ "    margin-top: 20px;\r\n"
        		+ "    \r\n"
        		+ "}\r\n"
        		+ "#b2{\r\n"
        		+ "    height: 30px;\r\n"
        		+ "    width: 100px;\r\n"
        		+ "    margin-left: 10px;\r\n"
        		+ "    background-color: red;\r\n"
        		+ "    color: white;\r\n"
        		+ "}\r\n"
        		+ "\r\n"
        		+ "</style>\r\n"
        		+ "\r\n"
        		+ "<body>\r\n"
        		+ "   \r\n"
        		+ "\r\n"
        		+ "    <div id=\"k1\">\r\n"
        		+ "        <select name=\"\" id=\"b1\">\r\n"
        		+ "            <option value=\"\">English</option>\r\n"
        		+ "            <option value=\"\">Hindi</option>\r\n"
        		+ "            <option value=\"\">Marathi</option>\r\n"
        		+ "        </select>\r\n"
        		+ "        <input type=\"button\" value=\"Sign In\" id=\"b2\">\r\n"
        		+ "    </div>\r\n"
        		+ "    <div id=\"a1\">NETFLIX</div>\r\n"
        		+ "    <div id=\"v1\">\r\n"
        		+ "        \r\n"
        		+ "    </div>\r\n"
        		+ "\r\n"
        		+ "    <div>\r\n"
        		+ "        <h1>Unlimited Movies ,TV Shows and More.</h1>\r\n"
        		+ "    </div>\r\n"
        		+ "    <div>\r\n"
        		+ "        <h3>Watch anywhere . Cancel Anytime.</h3>\r\n"
        		+ "    </div>\r\n"
        		+ "    <div>\r\n"
        		+ "        <h4>Ready To Watch? Enter your email to create or restart your membership.</h4>\r\n"
        		+ "    </div>\r\n"
        		+ "    <div>\r\n"
        		+ "        <input type=\"email\" id=\"l1\" placeholder=\"Enter address\">\r\n"
        		+ "        <input type=\"button\" value=\"Get Started >\" id=\"l2\">\r\n"
        		+ "    </div>\r\n"
        		+ "\r\n"
        		+ "</body>\r\n"
        		+ "\r\n"
        		+ "</html>");
      
    }
}
